theme = "catppuccin-mocha"

[providers]
default = ["desktopapplications", "calc", "websearch"]
empty = []

[[providers.prefixes]]
prefix = "?"
provider = "menus:help"

[placeholders]
"default" = { input = "Search (? for help)", list = "No Results" }

[providers.actions]
desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "new_instance", label = "new instance", bind = "shift Return" },
  { action = "new_instance:keep", label = "new+next", bind = "ctrl Return", after = "KeepOpen" },
  { action = "pin", bind = "ctrl p", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl n", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl m", after = "AsyncReload" },
]
