log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [["appLauncher", "Updates", "Workspaces"]]
center = ["WindowTitle"]
right = ["SystemInfo", ["Tray", "Clock", "Privacy", "Settings"]]

[updates]
check_cmd = "checkupdates; yay -Sy"
update_cmd = 'kitty @ launch --type os-window --no-response --hold yay'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "îœ²"
command = "nc -U /run/user/1000/walker/walker.sock"

[window_title]
truncate_title_after_length = 100

[clock]
format = "%a, %d %b %I:%M %p"

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock --immediate-render &"

audio_sinks_more_cmd = "pwvucontrol -t 4"
audio_sources_more_cmd = "pwvucontrol -t 3"

wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"

bluetooth_more_cmd = "blueman-manager"

remove_airplane_btn = true

[appearance]
scale_factor = 1.3
style = "Solid"

success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = ["#fab387", "#b4befe", "#cba6f7"]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
